const brainrots = {
  "Tung tung sahur": { base: 25, rarity: "Common" },
  "Capuchino assasino": { base: 25, rarity: "Common" },
  "Pipi potato": { base: 75, rarity: "Uncommon" },
  "Capuchina ballerina": { base: 80, rarity: "Uncommon" },
  "Noo my hotspot": { base: 85, rarity: "Uncommon" },
  "Salamino penguino": { base: 150, rarity: "Rare" },
  "Fluriflura": { base: 165, rarity: "Rare" },
  "Tim cheese": { base: 165, rarity: "Rare" },
  "Alessio": { base: 190, rarity: "Rare" },
  "Orangutini ananasini": { base: 375, rarity: "Epic" },
  "Brr brr patapim": { base: 415, rarity: "Epic" },
  "Udin din din din dun": { base: 450, rarity: "Epic" },
  "Pipi kiwi ": { base: 565, rarity: "Epic" },
  "Chef crabracadabra": { base: 1125, rarity: "Legendary" },
  "Boneca Ambalabu": { base: 1350, rarity: "Legendary" },
  "Cacto hipopotamo": { base: 1575, rarity: "Legendary" },
  "Sigma boy": { base: 1725, rarity: "Legendary" },
  "Bombini gusini": { base: 1875, rarity: "Legendary" },
  "Gorillo watermelondrillo": { base: 3375, rarity: "Mythic" },
  "Tric trac barabum": { base: 3380, rarity: "Mythic" },
  "Avocadini guffo": { base: 3750, rarity: "Mythic" },
  "Quivioli ameleonni": { base: 4125, rarity: "Mythic" },
  "Friggo camelo": { base: 4500, rarity: "Mythic" },
  "Glorbo fruttodrillo": { base: 5250, rarity: "Mythic" },
  "Pakrahmatmamat": { base: 6000, rarity: "Rare" },
  "La vacca saturnita": { base: 9000, rarity: "Secret" },
  "Tic tac sahur": { base: 10500, rarity: "Secret" },
  "Pot hotspot": { base: 120000, rarity: "Secret" },
  "Cocofanto elefanto": { base: 13500, rarity: "Secret" },
  "Job job sahur": { base: 15000, rarity: "Secret" },
  "La grande combination": { base: 16500, rarity: "Secret" },
  "Cuadramat & pak": { base: 18000, rarity: "Secret" },
  "Piccione maccina": { base: 18750, rarity: "Secret" },
  "67": { base: 26250, rarity: "Exotic" },
  "Esok sekolah": { base: 30000, rarity: "Exotic" },
  "Girafa celestre": { base: 33750, rarity: "Exotic" },
  "Chillin chilli": { base: 37500, rarity: "Exotic" },
  "Matteo": { base: 43500, rarity: "Exotic" },
  "Strawberelli flamingelli": { base: 45000, rarity: "Exotic" },
  "Ketupat kepat": { base: 46500, rarity: "Exotic" },
  "Torrtuginni dragonfrutini": { base: 48750, rarity: "Exotic" },
  "Ganganzelli trulala": { base: 60000, rarity: "OG" },
  "Strawberry elephant": { base: 75000, rarity: "OG" },
  "Crystallini ananasini": { base: 90000, rarity: "OG" },
  "Meowl ": { base: 101250, rarity: "OG" },
  "Spiuniru golubiru": { base: 112500, rarity: "OG" },
  "Crabbo limonetta": { base: 187500, rarity: "Divine" },
  "Swag soda": { base: 225000, rarity: "Divine" },
  "Chicleteira bicicleteira": { base: 262500, rarity: "Divine" },
  "Dragon cannelloni": { base: 300000, rarity: "Divine" },
  "Bananini manini": { base: 500000, rarity: "Godly" },
  "Namini meowini": { base: 750000, rarity: "Godly" }
};
